spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogdev?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: v8zVWYMPqzJ7cYyq
mybatis:
  mapper-locations: classpath:mapper/*.xml
